  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code again (needed for deploy context)
        uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8F0682C475184D338FC6464F85FF176F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D77EBBE4DCCB484F9A480C1EECA5C92D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B374FFA8A154791A7EC05E1E8C85CEE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'finacial-management-bot'
          slot-name: 'Production'
          package: ./release.zip
